//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FFBatch.Properties {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings2 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings2() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FFBatch.Properties.Strings2", typeof(Strings2).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Abort screen capture.
        /// </summary>
        internal static string abort_cap {
            get {
                return ResourceManager.GetString("abort_cap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a URL download aborted by user..
        /// </summary>
        internal static string aborted2 {
            get {
                return ResourceManager.GetString("aborted2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Application window will be minimized 1 second before recording starts..
        /// </summary>
        internal static string app_min_1 {
            get {
                return ResourceManager.GetString("app_min_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Audio wave format.
        /// </summary>
        internal static string Aud_wave {
            get {
                return ResourceManager.GetString("Aud_wave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sequential encoding autorun is enabled. Do you want to keep this setting?.
        /// </summary>
        internal static string auto_ask {
            get {
                return ResourceManager.GetString("auto_ask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Multi-file encoding autorun is enabled. Do you want to keep this setting?.
        /// </summary>
        internal static string auto_ask2 {
            get {
                return ResourceManager.GetString("auto_ask2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Autorun is disabled.
        /// </summary>
        internal static string autorun_dis {
            get {
                return ResourceManager.GetString("autorun_dis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Autorun is enabled.
        /// </summary>
        internal static string autorun_en {
            get {
                return ResourceManager.GetString("autorun_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a AUTOMATIC SHUTDOWN ENABLED.
        /// </summary>
        internal static string autoshut_en {
            get {
                return ResourceManager.GetString("autoshut_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a COMPUTER SHUTDOWN LAUNCHED.
        /// </summary>
        internal static string autoshut_st {
            get {
                return ResourceManager.GetString("autoshut_st", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a to avoid opossible overwritings..
        /// </summary>
        internal static string avoid_overw {
            get {
                return ResourceManager.GetString("avoid_overw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Batch concatenation is enabled, but no initial or end files were selected. Please choose either one of them or disable this setting..
        /// </summary>
        internal static string batch_concat_msg {
            get {
                return ResourceManager.GetString("batch_concat_msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Bigger size.
        /// </summary>
        internal static string big_size {
            get {
                return ResourceManager.GetString("big_size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Black.
        /// </summary>
        internal static string black {
            get {
                return ResourceManager.GetString("black", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Browsing url contents: Page.
        /// </summary>
        internal static string brow_page {
            get {
                return ResourceManager.GetString("brow_page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Browsing.
        /// </summary>
        internal static string browsing {
            get {
                return ResourceManager.GetString("browsing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Capturing in 1 second.
        /// </summary>
        internal static string capt_1 {
            get {
                return ResourceManager.GetString("capt_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Capturing in 2 seconds.
        /// </summary>
        internal static string capt_2 {
            get {
                return ResourceManager.GetString("capt_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Capturing in 3 seconds.
        /// </summary>
        internal static string capt_3 {
            get {
                return ResourceManager.GetString("capt_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Capturing terminated.
        /// </summary>
        internal static string capt_term {
            get {
                return ResourceManager.GetString("capt_term", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a To capture audio playback, virtual audio driver is required..
        /// </summary>
        internal static string capt_virtual {
            get {
                return ResourceManager.GetString("capt_virtual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Would you like to visit the project web site to check for new releases?.
        /// </summary>
        internal static string check_web_up {
            get {
                return ResourceManager.GetString("check_web_up", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Computer will.
        /// </summary>
        internal static string computer_will {
            get {
                return ResourceManager.GetString("computer_will", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a This filter allows to join videos with different qualities, it improves compatibility but it requires audio and video to be re-encoded. Parameters field can be left blank. NOTE: Only video files allowed..
        /// </summary>
        internal static string concat_vid_help {
            get {
                return ResourceManager.GetString("concat_vid_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Continue?.
        /// </summary>
        internal static string contin {
            get {
                return ResourceManager.GetString("contin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Custom.
        /// </summary>
        internal static string custom {
            get {
                return ResourceManager.GetString("custom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Deleting....
        /// </summary>
        internal static string deleting_f {
            get {
                return ResourceManager.GetString("deleting_f", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Deleting files....
        /// </summary>
        internal static string deleting_files {
            get {
                return ResourceManager.GetString("deleting_files", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Deleting processed files....
        /// </summary>
        internal static string deleting_proc {
            get {
                return ResourceManager.GetString("deleting_proc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Deleting source files....
        /// </summary>
        internal static string deleting_sourc {
            get {
                return ResourceManager.GetString("deleting_sourc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a In this mode audio/video files can be stream copied, provided they share qualities (size, codec, bitrate). NOTE: Not all containers are supported for stream copy. If playback issues occur or files are not joined, re-encoding may be required..
        /// </summary>
        internal static string demuxer_help {
            get {
                return ResourceManager.GetString("demuxer_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Destination folder is not empty. Continue?.
        /// </summary>
        internal static string dest_not_empty {
            get {
                return ResourceManager.GetString("dest_not_empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Different input folders to single output folder.
        /// </summary>
        internal static string dif_in_out_f {
            get {
                return ResourceManager.GetString("dif_in_out_f", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Download is in progress. Do you want to force quit?.
        /// </summary>
        internal static string down_p_ab {
            get {
                return ResourceManager.GetString("down_p_ab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Download is in progress, please abort before closing window..
        /// </summary>
        internal static string down_prog {
            get {
                return ResourceManager.GetString("down_prog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Download in progress.
        /// </summary>
        internal static string down_prog2 {
            get {
                return ResourceManager.GetString("down_prog2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Download.
        /// </summary>
        internal static string download {
            get {
                return ResourceManager.GetString("download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Dropped file is too big. Only text files under 1 MB are supported..
        /// </summary>
        internal static string drop_big {
            get {
                return ResourceManager.GetString("drop_big", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Please drop only one file..
        /// </summary>
        internal static string drop_one {
            get {
                return ResourceManager.GetString("drop_one", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error copying to clipboard..
        /// </summary>
        internal static string err_clipb {
            get {
                return ResourceManager.GetString("err_clipb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error trying to play URL with VLC:.
        /// </summary>
        internal static string err_pl_vlc {
            get {
                return ResourceManager.GetString("err_pl_vlc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a There was an error saving queue file..
        /// </summary>
        internal static string err_save_qu {
            get {
                return ResourceManager.GetString("err_save_qu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error saving track.
        /// </summary>
        internal static string err_save_track {
            get {
                return ResourceManager.GetString("err_save_track", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Test folder could not be created at TEMP location..
        /// </summary>
        internal static string err_test_temp {
            get {
                return ResourceManager.GetString("err_test_temp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error writing output folder:.
        /// </summary>
        internal static string err_write_out {
            get {
                return ResourceManager.GetString("err_write_out", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error writing to temp folder..
        /// </summary>
        internal static string err_write_temp {
            get {
                return ResourceManager.GetString("err_write_temp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error writing to destination folder. Please select another path, or ensure you have write permissions..
        /// </summary>
        internal static string error_writing {
            get {
                return ResourceManager.GetString("error_writing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a exceeds source duration..
        /// </summary>
        internal static string exc_dur {
            get {
                return ResourceManager.GetString("exc_dur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a External command returned an error on.
        /// </summary>
        internal static string ext_com_err {
            get {
                return ResourceManager.GetString("ext_com_err", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a External command executed successfully on.
        /// </summary>
        internal static string ext_com_ok {
            get {
                return ResourceManager.GetString("ext_com_ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a files can take a long time. Are you sure?.
        /// </summary>
        internal static string files_long_t {
            get {
                return ResourceManager.GetString("files_long_t", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Frame size.
        /// </summary>
        internal static string frame_size {
            get {
                return ResourceManager.GetString("frame_size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a in 60 seconds.
        /// </summary>
        internal static string in_60 {
            get {
                return ResourceManager.GetString("in_60", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Initializing download, please wait....
        /// </summary>
        internal static string init_wait {
            get {
                return ResourceManager.GetString("init_wait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Invalid capturing parameters.
        /// </summary>
        internal static string invalid_p_2 {
            get {
                return ResourceManager.GetString("invalid_p_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Invalid parameters for screen capturing..
        /// </summary>
        internal static string invalid_param {
            get {
                return ResourceManager.GetString("invalid_param", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Join files.
        /// </summary>
        internal static string join_files {
            get {
                return ResourceManager.GetString("join_files", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Language configuration was corrupted, please reinstall application..
        /// </summary>
        internal static string lang_corrupted {
            get {
                return ResourceManager.GetString("lang_corrupted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Logging for:.
        /// </summary>
        internal static string logging_f {
            get {
                return ResourceManager.GetString("logging_f", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Lower size.
        /// </summary>
        internal static string low_size {
            get {
                return ResourceManager.GetString("low_size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Missing files.
        /// </summary>
        internal static string missing_f {
            get {
                return ResourceManager.GetString("missing_f", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Please drop only one file..
        /// </summary>
        internal static string multi_drop {
            get {
                return ResourceManager.GetString("multi_drop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Multiple files dropped.
        /// </summary>
        internal static string multi_drop2 {
            get {
                return ResourceManager.GetString("multi_drop2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Multiplex Batch Jobs Manager.
        /// </summary>
        internal static string mux_jobs {
            get {
                return ResourceManager.GetString("mux_jobs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No initial or end files.
        /// </summary>
        internal static string no_concat_ef {
            get {
                return ResourceManager.GetString("no_concat_ef", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a none.
        /// </summary>
        internal static string none {
            get {
                return ResourceManager.GetString("none", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a could not be deleted..
        /// </summary>
        internal static string not_deleted {
            get {
                return ResourceManager.GetString("not_deleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Please select only one file to add its streams..
        /// </summary>
        internal static string one_track {
            get {
                return ResourceManager.GetString("one_track", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Downloading. Total count not available. Output folder count:.
        /// </summary>
        internal static string outf_count {
            get {
                return ResourceManager.GetString("outf_count", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Video: MP4 Stream copy.
        /// </summary>
        internal static string pr01 {
            get {
                return ResourceManager.GetString("pr01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Video: Convert audio track to AAC HQ 2 channels.
        /// </summary>
        internal static string pr02 {
            get {
                return ResourceManager.GetString("pr02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Video: Convert audio tracks to AC3 2 channels.
        /// </summary>
        internal static string pr03 {
            get {
                return ResourceManager.GetString("pr03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Video: Convert to ProRes MKV.
        /// </summary>
        internal static string pr04 {
            get {
                return ResourceManager.GetString("pr04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Video: Convert to H264 HQ + Source Audio.
        /// </summary>
        internal static string pr05 {
            get {
                return ResourceManager.GetString("pr05", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Video: Convert to H264 Ultrafast.
        /// </summary>
        internal static string pr06 {
            get {
                return ResourceManager.GetString("pr06", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Video: Convert to H265 HQ + Source Audio.
        /// </summary>
        internal static string pr07 {
            get {
                return ResourceManager.GetString("pr07", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Video: Resize 1280x720 H264-AAC.
        /// </summary>
        internal static string pr08 {
            get {
                return ResourceManager.GetString("pr08", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Video: Rotate 90 degress Clockwise to H264 + Source audio.
        /// </summary>
        internal static string pr09 {
            get {
                return ResourceManager.GetString("pr09", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Video: Rotate 90 degress CountercLockwise and Vertical Flip to H264 + Source audio.
        /// </summary>
        internal static string pr10 {
            get {
                return ResourceManager.GetString("pr10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Video: Rotate 90 degress CounterClockwise to H264 + Source audio.
        /// </summary>
        internal static string pr11 {
            get {
                return ResourceManager.GetString("pr11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Video: Rotate 90 degress Clockwise and Vertical Flip to H264 + Source audio.
        /// </summary>
        internal static string pr12 {
            get {
                return ResourceManager.GetString("pr12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Video: Rotate 180 degress to H264 + Source audio.
        /// </summary>
        internal static string pr13 {
            get {
                return ResourceManager.GetString("pr13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Video: Remove subtitles to MP4.
        /// </summary>
        internal static string pr14 {
            get {
                return ResourceManager.GetString("pr14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Audio: Convert to FLAC 16/44,1KHz 2 channels.
        /// </summary>
        internal static string pr15 {
            get {
                return ResourceManager.GetString("pr15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Audio: Convert to MP3 VBR HQ 2 ch embedded cover.
        /// </summary>
        internal static string pr16 {
            get {
                return ResourceManager.GetString("pr16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Audio: Convert to MP3 VBR HQ 2 ch.
        /// </summary>
        internal static string pr17 {
            get {
                return ResourceManager.GetString("pr17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Audio: Convert to MP3 CBR HQ 2 ch.
        /// </summary>
        internal static string pr18 {
            get {
                return ResourceManager.GetString("pr18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Audio: Convert to WAV 16/44,1KHz 2 channels.
        /// </summary>
        internal static string pr19 {
            get {
                return ResourceManager.GetString("pr19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Subtitle: Extract first subtitle track to SRT.
        /// </summary>
        internal static string pr20 {
            get {
                return ResourceManager.GetString("pr20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Image: Extract frame as image.
        /// </summary>
        internal static string pr21 {
            get {
                return ResourceManager.GetString("pr21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Record screen at 24 fps + Audio AAC to MKV.
        /// </summary>
        internal static string pr22 {
            get {
                return ResourceManager.GetString("pr22", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Record screen at 15 fps 1280x720 + Audio to MKV.
        /// </summary>
        internal static string pr23 {
            get {
                return ResourceManager.GetString("pr23", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Record screen at 30 fps Nvidia NVENC + Audio AAC to MKV.
        /// </summary>
        internal static string pr24 {
            get {
                return ResourceManager.GetString("pr24", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Record screen at 25 fps Intel QuickSync + Audio AAC to MKV.
        /// </summary>
        internal static string pr25 {
            get {
                return ResourceManager.GetString("pr25", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Join images at 1920px width to MP4 video.
        /// </summary>
        internal static string pr26 {
            get {
                return ResourceManager.GetString("pr26", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Set pre-input seeking parameter -ss.
        /// </summary>
        internal static string pre_ss {
            get {
                return ResourceManager.GetString("pre_ss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Press to cancel.
        /// </summary>
        internal static string press_c {
            get {
                return ResourceManager.GetString("press_c", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a queue file(s) were not found..
        /// </summary>
        internal static string queue_not_f {
            get {
                return ResourceManager.GetString("queue_not_f", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a File list successfully loaded..
        /// </summary>
        internal static string queue_warn {
            get {
                return ResourceManager.GetString("queue_warn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Quick YouTube channel/playlist download.
        /// </summary>
        internal static string quick_yt1 {
            get {
                return ResourceManager.GetString("quick_yt1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a - Go to YouTube channel main url, and click on VIDEOS tab..
        /// </summary>
        internal static string quick_yt2 {
            get {
                return ResourceManager.GetString("quick_yt2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a - Copy the url and paste on channel field..
        /// </summary>
        internal static string quick_yt3 {
            get {
                return ResourceManager.GetString("quick_yt3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a - Example:.
        /// </summary>
        internal static string quick_yt4 {
            get {
                return ResourceManager.GetString("quick_yt4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Recording test failed.
        /// </summary>
        internal static string rec_fail {
            get {
                return ResourceManager.GetString("rec_fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Remove selected items from list.
        /// </summary>
        internal static string rem_from_list {
            get {
                return ResourceManager.GetString("rem_from_list", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Horizontal flip.
        /// </summary>
        internal static string rot_flip {
            get {
                return ResourceManager.GetString("rot_flip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Rotate 90º clockwise.
        /// </summary>
        internal static string rotate1 {
            get {
                return ResourceManager.GetString("rotate1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Rotate 90º counter-clockwise.
        /// </summary>
        internal static string rotate2 {
            get {
                return ResourceManager.GetString("rotate2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Rotate 180º.
        /// </summary>
        internal static string rotate3 {
            get {
                return ResourceManager.GetString("rotate3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Screen capture.
        /// </summary>
        internal static string scr_cap {
            get {
                return ResourceManager.GetString("scr_cap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Screen capture test failed..
        /// </summary>
        internal static string scr_fail {
            get {
                return ResourceManager.GetString("scr_fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Screen capturing terminated unexpectedly. File may be truncated..
        /// </summary>
        internal static string scsr_term {
            get {
                return ResourceManager.GetString("scsr_term", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Select language.
        /// </summary>
        internal static string sel_lang {
            get {
                return ResourceManager.GetString("sel_lang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Select audio capture device.
        /// </summary>
        internal static string selc_dev {
            get {
                return ResourceManager.GetString("selc_dev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Skip selected items from encoding.
        /// </summary>
        internal static string skip_from_list {
            get {
                return ResourceManager.GetString("skip_from_list", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sort list before start?.
        /// </summary>
        internal static string sort_before {
            get {
                return ResourceManager.GetString("sort_before", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Please sort and check file list for items marked with status.
        /// </summary>
        internal static string sort_status {
            get {
                return ResourceManager.GetString("sort_status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Source files that could not be deleted due to failed encoding or file in use:.
        /// </summary>
        internal static string source_not_deleted {
            get {
                return ResourceManager.GetString("source_not_deleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Start screen capture.
        /// </summary>
        internal static string start_cap {
            get {
                return ResourceManager.GetString("start_cap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You can stop recording by pressing Control-Shift-P at any time..
        /// </summary>
        internal static string stop_any {
            get {
                return ResourceManager.GetString("stop_any", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Stop capturing.
        /// </summary>
        internal static string stop_capt {
            get {
                return ResourceManager.GetString("stop_capt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Stop processing.
        /// </summary>
        internal static string stop_proc {
            get {
                return ResourceManager.GetString("stop_proc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Streams.
        /// </summary>
        internal static string streams {
            get {
                return ResourceManager.GetString("streams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Subtitles.
        /// </summary>
        internal static string subtitles {
            get {
                return ResourceManager.GetString("subtitles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Too many files to be parsed.
        /// </summary>
        internal static string too_many_files {
            get {
                return ResourceManager.GetString("too_many_files", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Total.
        /// </summary>
        internal static string total {
            get {
                return ResourceManager.GetString("total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Transfer rate:.
        /// </summary>
        internal static string transfer_r {
            get {
                return ResourceManager.GetString("transfer_r", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Try with a screen capture preset and check encoding parameters..
        /// </summary>
        internal static string try_scr_pr {
            get {
                return ResourceManager.GetString("try_scr_pr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Processing will not continue after items with undefined duration (infinite)..
        /// </summary>
        internal static string undef_dur_all {
            get {
                return ResourceManager.GetString("undef_dur_all", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Items with undefined duration.
        /// </summary>
        internal static string undef_seq {
            get {
                return ResourceManager.GetString("undef_seq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a URL download successfully completed.
        /// </summary>
        internal static string url_down_c {
            get {
                return ResourceManager.GetString("url_down_c", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a URL download complete.
        /// </summary>
        internal static string url_down_c2 {
            get {
                return ResourceManager.GetString("url_down_c2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Version.
        /// </summary>
        internal static string version {
            get {
                return ResourceManager.GetString("version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a There were warning messages during queue download:.
        /// </summary>
        internal static string warn_down {
            get {
                return ResourceManager.GetString("warn_down", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a WARNING: File.
        /// </summary>
        internal static string warning_file {
            get {
                return ResourceManager.GetString("warning_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a was NOT replaced.
        /// </summary>
        internal static string warning_not_rep {
            get {
                return ResourceManager.GetString("warning_not_rep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a warning(s) during last session.
        /// </summary>
        internal static string warnings_last_s {
            get {
                return ResourceManager.GetString("warnings_last_s", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a White.
        /// </summary>
        internal static string white {
            get {
                return ResourceManager.GetString("white", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Incorrect capture duration.
        /// </summary>
        internal static string wrong_c_dur {
            get {
                return ResourceManager.GetString("wrong_c_dur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a YouTube URL field is empty..
        /// </summary>
        internal static string yt_url_blank {
            get {
                return ResourceManager.GetString("yt_url_blank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a YouTube URL is too short..
        /// </summary>
        internal static string yt_url_sh {
            get {
                return ResourceManager.GetString("yt_url_sh", resourceCulture);
            }
        }
    }
}
